### ISSUE TITLE
PVC Minigame - Simple

### ISSUE THREAD

**Issue by asyncmeonov** [Gorea235/Uni-UniversityDominationA3#10]
### Space invaders clone

To do:
- [x] Design for attacking goose (64 x 32-64px)
- [x] Design for bonus Central Hall spaceship (84x32px)
- [x] Design for player (size should not exceed 84x64px, but is up for discussion)
- [x] Design for player bullet (8x8px)
- [x] Design for geese "bullet" (it should definitely be 8x8px poop)
- [x] Devise bonuses that are transferred to the main game
- [x] Design the background (assume full-HD screen 1920x1080px with a viewport for the game within it)

**Comment by asyncmeonov** [comment]
I am providing a concept sketch of the minigame. Note that as stated above the full windows is considered to be 1920x1080 and the "arcade window" is 1032x774px (4:3 aspect ratio). All the unit sizes have been caculated in respect to that window size and will be adjusted proportionally if any changes occur. A change that is to be noted from the original concept is the inclusion of a timer which will restrict the minigame from being too long.
![concept](https://user-images.githubusercontent.com/6080674/35615763-0e76a318-066b-11e8-9ae6-933c6557d99e.png)

**Comment by luvies** [comment]
The commit 47c120d added a bunch of assets that were needed

**Comment by luvies** [comment]
Commit a8703b8 added the final functionality I think we will need. So far, I think the simple minigame is now done. However, we still need to be able to switch in and out of scenes with the main game, so we don't lose everything when we switch to the new scene. To do this, I think we will utilise #6 to save the entire game-state in a static variable, and then reload it once the minigame is complete. The benefit of doing it this way, is that we use systems we need anyway, and it is minigame-agnostic, meaning the exact same system will work for both minigames without changes.

**Comment by luvies** [comment]
Final note on this issue; the minigame logic has been completed, so the scene can be simply loaded when needed, and once it's finished the main game will detect the score and apply it separately.
