### ISSUE TITLE
Add more Unit Tests

### ISSUE THREAD

**Issue by luvies** [Gorea235/Uni-UniversityDominationA3#13]
The current unit tests all work, but we haven't added more to account for the new functionality. This should really be done.

**Comment by luvies** [comment]
I've added unit tests for handling the saving, loading and memento functions, however the rest of the code doesn't seem to be very testable, or we have modified existing functions.

**Comment by asyncmeonov** [comment]
@bnp502 to be noted that for the testing deliverables these unit tests are added and their functionality does not need our alternative GUI testing approach.

**Comment by luvies** [comment]
As many functions as possible are now tested for, and as such no more unit tests can be added at this time without refactoring code to extract portions for testing. The rest should be done via acceptance testing.
