### ISSUE TITLE
General deliverable discussion

### ISSUE THREAD

**Issue by asyncmeonov** [Gorea235/Uni-UniversityDominationA3#15]
This is a general deliverable monitor issue. All progress will be marked here.

1. Change3.pdf
    - [x] Summary of changes
    - [x] update on GUI report
      - [x] justification of update in Changes3.pdf
    - [x] update on Methods and Plans report
    - [x] Gantt for assessment 4
      - [x] justification of update in Changes3.pdf
    - [x] update on Test report
      - [x] justification of update in Changes3.pdf
      - [x] testing plan and results
    - [x] update on Risk Assessment and Mitigation report
      - [x] justification of update in Changes3.pdf

2. Impl3.pdf
    - [x] New concrete UML
    - [x] Update on requirements
    - [x] Implementation description
    - [x] Changes
    - [x] New features

3. Additional
    - [x] Updated user manual
    - [x] Website prepared with links to repo
    - [x] url3.txt probably having links to repo as well

**Comment by asyncmeonov** [comment]
I wanted to point out a couple of things for Change3.pdf:

The _justification_ of each report (GUI, Methods & Plans, Test and Risk & Mitigation) should happen after you've updated the corresponding report so you can actually have things to justify. Otherwise the things don't really make sense and is impossible to write (because you don't really have a change to write for). 

I've noticed there is a bit of confusion at what the "change" actually is. It is not a change of projects, but its a change in management. We are not interested in what we did for the hex game anymore, the changes we are explaining is from their assessment 2. For now actually only the Risk update is on point. I do hope you understand what I mean, because this is crucial. I also encourage you to come forward if there is anything you find not right both about the documents or about what I say.

**Comment by asyncmeonov** [comment]
I've written a bit on the GUI update and GUI change, do check them when you can for proof reading and shoot down at will

**Comment by asyncmeonov** [comment]
Jobs TBD, please distribute them by yourselves:

- make an editable Unit test doc from https://sepr-team-margaret.github.io/content/UnitT2.pdf and put it in Deliverables > Additional Submissions
- expand the user manual to cover all functionality of our game
- method report update/ justification needs rework
- test report/ justification needs doing

**Comment by luvies** [comment]
This is the last item we need to do for assessment 3, so once it's done we can close this issue and lock the repo to read-only.

**Comment by luvies** [comment]
Deliverables are now done, closing issue
