### ISSUE TITLE
Public self assessment discussion

### ISSUE THREAD

**Issue by asyncmeonov** [Gorea235/Uni-UniversityDominationA3#16]
Please add a comment with the name of each person in the group and the mark (from 0 to 10) you give to him. The end mark for someone would be the dominant one, or in event of disagreement: the average value of all the marks.

An example voting comment (of course, removing yourself when writing the comment):

> Luke: 10 ; Angel: 10 ; Dan: 10; Jordan: 10; Ben: 10; Mingrui: 10

Please do it **PRIOR 11:30AM** otherwise your vote would not be considered. This has been discussed and is agreed upon. The self assessment form is submitted for assessment 3 as it serves as an incentive, because we do not aim to wait and mark down people out of spite during assessment 4.

**Comment by asyncmeonov** [comment]
Luke: 10 ; Dan: 10; Jordan: 5; Ben: 10; Mingrui: 10

**Comment by Skyteens** [comment]
Luke: 10 ; Dan: 10; Jordan: 4; Ben: 10; Mingrui: 10

**Comment by Skyteens** [comment]
and angel :10

**Comment by bnp502** [comment]
Luke: 10; Dan: 10; Jordan: 6; Angel: 10; Mingrui: 10
If we were including ourselves I'd give Ben a 6/7

**Comment by asyncmeonov** [comment]
Just to point out "...removing yourself when writing the comment"

**Comment by luvies** [comment]
I think I made my choices clean in the SelfAss3.pdf

**Comment by asyncmeonov** [comment]
Logan Paul quotes are not considered academically acceptable.

**Comment by luvies** [comment]
Then I'd go with Ben's scoring as well


*ʷʰᵃᵗ'ˢ ᵘᵖ ˡᵒᵍᵃⁿᵍ ʳᵉᵐᵉᵐᵇᵉʳ ᵗᵒ ᵈᵃᵇ ᵒⁿ ᵗʰᵒˢᵉ ʰᵃᵗᵉʳˢ*

**Comment by Skyteens** [comment]
wait is this peer assess or self assess cos i thought self assess is when you judge yourself

**Comment by asyncmeonov** [comment]
For self-assessing in SEPR context, the "self" is the team. https://www.cs.york.ac.uk/student/assessment/collect/distribute/get-asm/COM00008I178/A/001/ (I am not sure if its going to open from this link, but this is the big assessment document that was handed at the beginning) section 2.1 is the detailed explanation of self-assessing.

**Comment by ml1652** [comment]
Luke 10 Ben 10 Jordan 7 Angel 10 Dan 10

**Comment by hatoa** [comment]
Angel: 10. Ben: 10 (Good show btw). Mingrui: 10. Luke: 10. Jordan: 5.

**Comment by Nicodaw** [comment]
The collective end vote was

**Comment by asyncmeonov** [comment]
The collective end decision is

Ben: 10
Jordan: 6 (average 5.8 rounded)
Luke: 10
Mingrui: 10
Dan: 10
Angel: 10
