### ISSUE TITLE
Implement AI players

### ISSUE THREAD

**Issue by luvies** [Gorea235/Uni-UniversityDominationA3#5]
If there are less than 4 human players in the game, then the remaining players should be controlled via an AI.

We need to decide whether to implement an actual AI that attempts to make decisions, or whether to just make it static (i.e. make it not do anything).

**Comment by luvies** [comment]
The game should have at least 2 human players, but the requirements also state that we should give the option to allow less than 4 players total in the game. 

It seems that the 4 player limit is the maximum, not the given, so we should allow for 2-4 players (inclusive).

**Comment by asyncmeonov** [comment]
@Gorea235 Requirements should be changed as a necessity from the brief is an AI player always being present during a 2 player game. So essentially at a minimum you have actually 3 players in game and the fourth should be with the optionality of human/ai/none.

**Comment by luvies** [comment]
That's true. For the menu, it might make sense to give 4 sections for player selection, with the following layout

- 2 sections to allow selection of college by the players
- 1 section which allows the selection between AI and Human, and if human allows college selection
- 1 section that allows selection as previous, but also allows for 'None'

We could half-merge the last 2 sections, in that if 1 has an AI or player currently selected, the other allows for a 'None' selection, regardless of its position.

**Comment by luvies** [comment]
For simplicity's sake, we've gone with at least 2 human players with the rest as AI
