### ISSUE TITLE
Sector cleanup

### ISSUE THREAD

**Issue by luvies** [Gorea235/Uni-UniversityDominationA3#8]
The sectors have a huge amount of polygons, which is completely unnecessary as they are very square-like buildings. We should simplify the models in order to reduce load times and overall size.

**Comment by asyncmeonov** [comment]
Load times will benefit a lot. This is a [before](https://puu.sh/zdv9r/ef56f3f1af.png) and [after](https://puu.sh/zdvhj/f16e035068.png) of sector one with provided statistics.
