### ISSUE TITLE
Allow users to specify how many units to move

### ISSUE THREAD

**Issue by luvies** [Gorea235/Uni-UniversityDominationA3#9]
Currently, when moving units, the user will move all the units in a sector to the selected one. This means that the user has little-to-no control on how units are allocated over the sectors.

While not a requirement issue, it might be worth thinking about now, since we are working on a proper menu system (see #7), and it would greatly improve the user experience (and, if done well, might improve the chances of being picked next)

**Comment by asyncmeonov** [comment]
I will say it again here as I do think we have to step it down a notch with any functionality that has for justification only "improving gameplay". Allowing splitting will lead to the problem of players expanding too fast, which will lead to us needing to expand the map and although that was mentioned in #3 these additions are just too much. It is painfully ironic, but I do implore that our fun game be left as bland as possible.

**Comment by luvies** [comment]
While I do agree with the fact that it might be too much, it is worth a thought, since it does make the game very limiting to play. I labelled it enhancement since this issue was mainly one of gameplay, which isn’t a requirement for A3.

Since we will leave this issue to the back-burner for now, I will put more effort into making the mini-game unique (see #11), since we can realistically to anything for it.

**Comment by luvies** [comment]
Do we plan on furthering this at all, or shall we just close?

**Comment by asyncmeonov** [comment]
I am still vouching for not bothering. There is no real reason we would even improve upon the main game after the minigame is so fun.
Joke aside, I don't think its worth because it is subjectively justifiable in terms of deliverables and we can focus our time on more important things like the deliverables or actually beta testing (with [real human beans](https://www.youtube.com/watch?v=-DSVDcw6iW8)) if we can.

**Comment by luvies** [comment]
After better understanding of the game, I realise that the number is the level of a single unit, not the amount of units. Thus, this is redundant.
